### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by vikas027** [ruo91/docker-vsftpd#1]
I follow the commands but unable to login, got below error.

``` bash
ftp 192.168.1.93
Connected to 192.168.1.93 (192.168.1.93).
220 Welcome to Yongbok.net FTP service.
Name (192.168.1.93:root): ruo91
331 Please specify the password.
Password:
530 Login incorrect.
Login failed.
```

And this in the container logs

``` bash
root@vsftpd:/# tail -f /var/log/vsftpd.log
Sun Jul  5 00:23:28 2015 [pid 23] CONNECT: Client "192.168.1.62"
Sun Jul  5 00:23:44 2015 [pid 22] [ruo91] FAIL LOGIN: Client "192.168.1.62"
```

**Comment by ruo91** [comment]
Please set the password to 8 characters or less.
And.. bug fixed https://github.com/ruo91/docker-vsftpd/commit/4c72d7832dd22d97d0340b82333435a0a971210c#diff-e157fe5e4f47763c3f512b20f992219cR4 thx :)

**Comment by ruo91** [comment]
Bug fixed

**Comment by arnepaulsen** [comment]
Look in the Docker log for the container name. It will have the vsftp generated password that is hashed from the one you supplied in the run command.

That's why they call it "very secure".
